#!/usr/bin/env python3
"""Generate our six-tap, 64-phase, Q12 Lanczos-2 downsampling filters.

Weights use sinc(x / ratio) * sinc(x / (2 * ratio)), normalized to unity.
No vendor coefficient data is used. Run from any directory to regenerate.
"""
import math
from pathlib import Path


def coefficients(numerator, denominator):
    ratio = numerator / denominator
    rows = []
    for phase in range(64):
        weights = []
        for tap in range(6):
            x = (tap - 2 - phase / 64) / ratio
            sinc = lambda t: math.sin(math.pi * t) / (math.pi * t) if t else 1.0
            weights.append(sinc(x) * sinc(x / 2) if abs(x) < 2 else 0.0)
        row = [round(w * 4096 / sum(weights)) for w in weights]
        row[max(range(6), key=lambda i: weights[i])] += 4096 - sum(row)
        rows.append(row)
    return rows


def generate():
    text = "/* SPDX-License-Identifier: GPL-2.0-only */\n"
    text += "/* Generated by tools/generate-scaler-coefficients.py; original mathematical filters. */\n"
    for n, d in ((3, 2), (4, 3), (2, 1)):
        text += f"static const short filter_{n}_{d}[64][6] = {{\n"
        text += "".join("\t{ " + ", ".join(map(str, row)) + " },\n" for row in coefficients(n, d))
        text += "};\n"
    return text


if __name__ == "__main__":
    (Path(__file__).resolve().parents[1] / "driver/gc573_scaler_coefficients.h").write_text(generate())
